### ISSUE TITLE
Update license of unshare_auth branch and gtc branch

### ISSUE THREAD

**Issue by ericfranz** [OSC/bc_osc_tensorboard#1]
Should use this license: https://github.com/stanford-rc/sh_ood-apps/blob/master/LICENSE

Also might want to put a comment in the auth_rev_proxy linking back to https://github.com/stanford-rc/sh_ood-apps which is the source of it.

If we want a different license we would then replace the reverse proxy with our own.

**Comment by johrstrom** [comment]
I've copied [their license here](https://github.com/OSC/bc_osc_tensorboard/blob/42953a21ed90609c486b52fb3743eb246279ed2b/licenses/authrevproxy.LICENSE) and added this note about [authrevproxy](https://github.com/OSC/bc_osc_tensorboard/blob/42953a21ed90609c486b52fb3743eb246279ed2b/README.md#authrevproxy) in the README.

Does that cover your concerns?
